name: Deploy site

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  # 1. サイトをビルドするジョブ
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install and Build 🔧
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          pip3 install --upgrade nbconvert
          export JEKYLL_ENV=production
          bundle exec jekyll build

      - name: Upload artifact 📤
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # 2. ビルドしたデータをPagesに公開するジョブ
  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
